version: '3.3'
services:
  webserver:
    image: dockerhub.ratnikovmikhail.ru/projects/drawitbook_com/web_server
    ports:
      - "8099:80"
    depends_on:
      - fpm
    networks:
      - inner
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.projects == true ]
  fpm:
    image: dockerhub.ratnikovmikhail.ru/projects/drawitbook_com/php
    networks:
      - inner
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.projects == true ]

  cronjob:
    image: dockerhub.ratnikovmikhail.ru/projects/drawitbook_com/cronjob
    networks:
      - inner
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.projects == true ]

#Docker Networks
networks:
  inner:
    driver: overlay
    attachable: true