version: '3.3'
services:
    selenium-hub:
        image: selenium/hub:latest
        networks:
            - network
    #    ports:
    #        - "4442:4442"
    #        - "4443:4443"
    #        - "4445:4444"
    chrome:
        image: selenium/node-chrome:beta
        shm_size: 2gb
        depends_on:
            - selenium-hub
        networks:
            - network
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    webserver:
        build:
            context: .
            dockerfile: docker/dev/nginx/Dockerfile
            labels:
                dev: true
        image: 'drawitbook_com/webserver:dev'
        ports:
            - "8111:80"
        volumes:
            - ./www:/var/www/html
        networks:
            - network
        depends_on:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: docker/dev/php/Dockerfile
            labels:
                dev: true
            args:
                - USER_NAME=${USER_NAME}
                - USER_ID=${USER_ID}
                - USER_GROUP_NAME=${USER_GROUP_NAME}
                - USER_GROUP_ID=${USER_GROUP_ID}
        image: 'drawitbook_com/php:dev'
        volumes:
            - ./www:/var/www/html:cached
            - ./docker/dev/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./docker/dev/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/dev/php/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
        environment:
            - XDEBUG_CONFIG=mode=debug client_port=9003
            - PHP_IDE_CONFIG=serverName=docker
            - APP_ENV=local
        env_file:
            - .env
        networks:
            - network
    webpack:
        build:
            context: .
            dockerfile: docker/dev/webpack/Dockerfile
            args:
                - NPM_TOKEN=${NPM_TOKEN}
            labels:
                dev: true
        image: 'drawitbook_com/webpack:dev'
        command: ["npm", "run", "dev"]
        volumes:
            - ./www:/var/www/html
        environment:
            - NODE_ENV=development
        env_file:
            - .env
        networks:
            - network
    minio:
        image: 'minio/minio:RELEASE.2023-04-28T18-11-17Z.fips'
        volumes:
            - ./docker/dev/data/minio:/data
        ports:
            - "8112:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /data --console-address ":9001"
        networks:
            - network
    mclient:
        image: 'minio/mc'
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
            /usr/bin/mc mb minio/${MINIO_IMAGES_BUCKET};
            /usr/bin/mc anonymous set download minio/${MINIO_IMAGES_BUCKET};
            "
        networks:
            - network
    elasticsearch:
        build:
            context: .
            dockerfile: docker/dev/elasticsearch/Dockerfile
        volumes:
            - ./docker/dev/data/elasticsearch:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - cluster.routing.allocation.disk.threshold_enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
            - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
        depends_on:
            - fpm
        networks:
            - network

networks:
    network: