version: '3.3'
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    restart: unless-stopped
    networks:
        - main_network
#    ports:
#        - "4442:4442"
#        - "4443:4443"
#        - "4445:4444"
  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    restart: unless-stopped
    depends_on:
        - selenium-hub
    networks:
        - main_network
    environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  webserver:
    build:
      context: .
      dockerfile: docker/dev/nginx/Dockerfile
      labels:
        dev: true
    image: 'dev/drawitbook_com/webserver'
    restart: unless-stopped
    ports:
      - "8099:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - main_network
    depends_on:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: docker/dev/php/Dockerfile
      labels:
        dev: true
      args:
        - USER_NAME=${USER_NAME}
        - USER_ID=${USER_ID}
        - USER_GROUP_NAME=${USER_GROUP_NAME}
        - USER_GROUP_ID=${USER_GROUP_ID}
    image: 'dev/drawitbook_com/php'
    volumes:
      - ./www:/var/www/html
      - ./docker/dev/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/dev/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/dev/php/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    environment:
      - XDEBUG_CONFIG=mode=debug client_port=9003 client_host=${XDEBUG_REMOTE_HOST}
      - PHP_IDE_CONFIG=serverName=docker
      - APP_ENV=local
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - main_network
  webpack:
    build:
      context: .
      dockerfile: docker/dev/webpack/Dockerfile
      args:
        - NPM_TOKEN=${NPM_TOKEN}
      labels:
        dev: true
    image: 'dev/drawitbook_com/webpack'
    volumes:
      - ./www:/var/www/html
    ports:
      - "10008:10008"
    environment:
      - WEBPACK_DEVSERVER_IN_PORT=10008
      - NODE_ENV=development
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - main_network

networks:
  main_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}/${SUBNET_MASK}