#!/bin/bash

docker exec -t drawitbookru_fpm_1 composer run phprector

DIFF=`git diff --shortstat "www/app"`
if [[ $DIFF != "" ]]; then
    git commit -a -m "style(phprector): Приведение к стандарту" --author="PhpRectorBot <phprector@example.com>"
fi