name: Check & fix styling

on: [push]

jobs:
    code_analysis:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none

            -   name: Copy .env
                run: |
                    cd www && cp .env.example .env

            -   name: Add HTTP basic auth credentials
                run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/www/auth.json

            -   name: Composer install
                run: |
                    cd www && composer install

            -   name: Php Cs Fixer Fix
                run: |
                    cd www && composer php-cs-fixer --ansi

            -   name: Commit changes Php Cs Fixer
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: "style(php-cs-fixer): Приведение к стандарту"

            -   name: PhpRector Fix
                run: |
                    cd www && composer phprector --ansi

            -   name: Commit changes PhpRector
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: "style(php-rector): Приведение к стандарту"